[package]
name = "medi-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
