name: cd

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install tools with mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Extract version number
        run: echo "MEDI_RS_VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

      - name: Check format
        run: mise run check-format

      - name: Lint
        run: mise run lint

      - name: Test
        run: mise run test

      - name: Check examples
        run: mise run check-examples

      - name: Run examples
        run: mise run run-examples

      - name: Check docs
        run: mise run check-docs

      - name: Publish crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
        run: mise run publish -- "$MEDI_RS_VERSION"
